baseurl = "http://masiqi.github.io"
languageCode = "zh-cn"
title = "马思奇的博客"
[permalinks]
  post = "/:year/:month/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
  description = "马思奇的博客"
  author = "Ma siqi"
  gaCode = "UA-61199866-1"
  disqusShortname = "masiqi"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIdAnchors = true
  extensions = ["hardLineBreak"]


[[menu.main]]
  name = "关于我"
  pre = "<i class='fa fa-heart'></i>"
  weight = -110
  identifier = "about"
  url = "/about/"


